biolib_version: 2
modules:
    main:
        image: 'local-docker://inverse:latest'
        command: python3 run.py
        input_files:
            - COPY / /
        output_files:
            - COPY /output/ /
        source_files: []

        required_cpu_in_nano_shares: 4000000000
        required_memory_in_bytes: 16000000000
main_output_file: /output.md
arguments:
    -
        default_value: sample.pdb
        description: 'Enter your protein structure as a PDB file:'
        key: ''
        key_value_separator: ' '
        required: true
        type: file

    -
        default_value: 1
        description: 'Number of sequences to sample:'
        key: '--num-samples'
        key_value_separator: ' '
        required: false
        type: number 

    -
        default_value: ''
        description: 'Score the sequences by log likelihood?:'
        key: ''
        key_value_separator: ' '
        required: false
        type: toggle 
        options:
          'off': ''
          'on': '--score'
    -   
        default_value: ''
        description: 'Mask your backbone:'
        key: ''
        key_value_separator: ''
        type: toggle
        required: false
        options: 
            'off': ''
            'on': '--mask'
        sub_arguments:
            '--mask':
                -
                    key: ''
                    key_value_separator: ''
                    default_value: ''
                    description: 'Add the sequence masking ranges, e.g.: 10-15,21-25'
                    type: text
                    required: false

citation:
    entry_type: article
    author: Chloe Hsu, Robert Verkuil, Jason Liu, Zeming Lin, Brian Hie, Tom Sercu, Adam Lerer, Alexander Rives
    title: "Learning inverse folding from millions of predicted structures"
    journal: bioRxiv
    year: '2022'
    volume: ' '
    doi: 'doi:10.1101/2022.04.10.487779-'


